controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity

    gripper_controller:
      type: effort_controllers/GripperActionController
      joints:
        - gripper_joint
